name: experiment_catalogue
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.3.0+1
  bloc: ^8.1.4
  camerawesome: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_serializable: ^6.9.3
  just_audio: ^0.9.43
  pocketbase: ^0.21.0
  video_player: ^2.9.2

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
