name: experiment_catalogue
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  attributed_text: ^0.4.4
  auto_route: ^9.3.0+1
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  camerawesome: ^2.1.0
  chewie: ^1.10.0
  connectivity_plus: ^6.1.2
  equatable: ^2.0.7
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.10.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter

  flutter_webrtc: ^0.12.11
  follow_the_leader: ^0.0.4+8
  graphic: ^2.5.1
  http: ^1.3.0
  http_parser: ^4.1.2
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_serializable: ^6.9.3
  just_audio: ^0.9.43
  media_kit_libs_linux: ^1.1.0
  overlord: ^0.0.3+5
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pocketbase: ^0.21.0
  rich_field_controller: ^0.2.1
  rxdart: ^0.28.0
  shared_preferences: ^2.4.0
  socket_io_client: ^3.0.2
  super_editor: ^0.3.0-dev.20
  super_editor_markdown: ^0.1.7
  uuid: ^4.5.1
  video_player: ^2.9.3
  video_player_media_kit: ^1.0.5
  weather: ^3.1.1
  web_socket_client: ^0.1.5

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
